version: '3.8'
services:
  web:
    build: .
    container_name: 'web-platzi'
    ports:
      - "8080:5000"
    environment:
      - FLASK_APP=platzi-api
      - FLASK_ENV=dev
      - PLATZI_DB_URI=mongodb+srv://${DB_USER}:${DB_PASS}@${DB_SERVER}
